spring:
  application:
    name: bingo-map

  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
    cache: false

  datasource:
    # --- 집 (xe) ---
    #url: jdbc:oracle:thin:@//localhost:1521/xe
    #password: 1234

    # 현재 학원 설정
    url: jdbc:oracle:thin:@//localhost:1521/orcl
    username: scott
    password: tiger
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: none
#0930 kdk sql문 출력 해제
    show-sql: false
    database-platform: org.hibernate.community.dialect.OracleLegacyDialect
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080